### ISSUE TITLE
Non-animated tags do not respect case sensitivity

### ISSUE THREAD

**Issue by DetermineAbsurd** [HooferDevelops/Custom-User-Tags#3]
Included is a screenshot showcasing the bug. This remains constant in all views of the user tags as well, not just the settings page for the User Tags.
![HD09jVWI8r](https://user-images.githubusercontent.com/12719642/98421808-3a2a6580-2058-11eb-832a-35d7ae5cd593.gif)

**Comment by HooferDevelops** [comment]
fixed, sorry about that.

**Comment by DetermineAbsurd** [comment]
Not a problem. Thanks for the quick fix 😄
