### ISSUE TITLE
Attempting to add an entry to user tags crashes the client and causes a reload.

### ISSUE THREAD

**Issue by R3D4CTED** [HooferDevelops/Custom-User-Tags#5]

**Comment by proudmuslim-dev** [comment]
Experiencing the same issue, seconded

**Comment by Patrosi73** [comment]
Same issue

**Comment by myerDOT** [comment]
This happened to me after I tried to create an entry, then exited the menu while it was still default value because I forgot to copy the person's user ID. Trying to go back into the menu causes a crash.

**Comment by myerDOT** [comment]
A temporary fix for my particular issue can be fixed by simply going to `settings/Custom-User-Tags.json` and deleting the broken entry.

**Comment by proudmuslim-dev** [comment]
> A temporary fix for my particular issue can be fixed by simply going to `settings/Custom-User-Tags.json` and deleting the broken entry.

Thanks, trying this now

**Comment by zoomie-del** [comment]
> A temporary fix for my particular issue can be fixed by simply going to `settings/Custom-User-Tags.json` and deleting the broken entry.

where is the broken entry

**Comment by myerDOT** [comment]
> > A temporary fix for my particular issue can be fixed by simply going to `settings/Custom-User-Tags.json` and deleting the broken entry.
> 
> where is the broken entry

for me, the issue occurred after i created a new user entry and forgot to fill in the fields
so i deleted the entry with user id = 0000000000000000000

**Comment by HooferDevelops** [comment]
#6 fixed in this pull request
